# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f793d7b4e65ebc0428fae4e2fac9d556f37faa3de7c1007753fab9852e208bb8de4ad66b34a26492e455946975b19a50cc5c8a045174979d20335e0cb95b9a7f

test:
  secret_key_base: 646958937aebb03db840c151f83c8bdf7c91bdacdad1f22275b97297e8d730867e146a190f27a8db71563a619feb2b40ed2244f260bdeea4d5b33bc077c35e65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
